---
app:
  name: Notify
  baseUrl: http://localhost:3000/notify
  assets: []
  session:
    httpsOnly: false
    secret:
      - thisisasecret
    name: notify.sid
    cookie:
      maxAge: 3600
  db:
    type: sqlite
    database: data/data.db
    timezone: 'Z'
    synchronize: false
    dropSchema: false
    migrationsRun: false
    logging: true
    entities:
      - src/entities/*.ts
    migrations:
      - src/migrations/*.ts
    cli:
      migrationsDir: src/migrations
      entitiesDir: src/entities
