---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:12
    commands:
      - npm install
      - npm run lint
      - npm run bootstrap
      - npm run compile:lib
      - npm run test:ci
      - npm run compile:esm
---
kind: signature
hmac: 234de0a22115096452d098a0e6397fec9f39a6706b1a5e556387b0a6e432ee71

...
