---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:12
    commands:
      - npm install
      - npm run lint
      - npm run bootstrap
      - ./node_modules/.bin/jest
      - ./node_modules/.bin/lerna exec rondo -- build --esm
---
kind: signature
hmac: a49a1e7c428472d0237bb2ba73511965607384f45114941b869c6a9eff7aef70

...
