import * as fs from 'fs'
import {argparse, arg} from '@rondo.dev/argparse'
import {join} from 'path'
import {info} from '../log'

export async function exportDir(...argv: string[]) {
  const args = argparse({
    project: arg('string', {default: '.', positional: true}),
    dir: arg('string', {default: 'src/migrations'}),
    out: arg('string', {default: 'src/migrations/index.ts'}),
    help: arg('boolean', {alias: 'h'}),
  }, exportDir.help)
  .parse(argv)

  const dir = join(args.project, args.dir)
  const out = join(args.project, args.out)

  const index = '// This file has been autogenerated by exportDir script\n' +
  fs.readdirSync(dir)
  .filter(item => item.endsWith('.ts') && !item.endsWith('index.ts'))
  .map(item => item.replace(/\.ts$/, ''))
  .sort()
  .map(item => `export * from './${item}'\n`)
  .reduce((str, item) => str += item, '')

  info('Writing to %s', out)
  fs.writeFileSync(join(dir, 'index.ts'), index)
}
exportDir.help = 'Create index.ts and generate import statements for files ' +
  'in the same directory'
