/* This file was generated by rondo intergen script */
/* tslint:disable */

export interface BaseEntity {
  id: number
  createDate: string
  updateDate: string
}

export interface Role {
  name: string
  id: number
  createDate: string
  updateDate: string
}

export interface Team {
  name: string
  userId: number
  user?: User
  userTeams: UserTeam[]
  id: number
  createDate: string
  updateDate: string
}

export interface User {
  username: string
  firstName: string | null
  lastName: string | null
  emails: UserEmail[]
  password?: string
  sessions: Session[]
  userTeams: UserTeam[]
  id: number
  createDate: string
  updateDate: string
}

export interface UserEmail {
  email: string
  user?: User
  userId?: number
  id: number
  createDate: string
  updateDate: string
}

export interface Session {
  id: string
  expiredAt: number
  user?: User
  userId: number
  json: string
}

export interface UserTeam {
  user: User
  userId: number
  team?: Team
  teamId: number
  role?: Role
  roleId: number
  id: number
  createDate: string
  updateDate: string
}
